export const PROD_TITLE="title"
export const PROD_DESC="description"
export const PROD_IMAG="image"
export const PROD_PRICE="price"
export const PROD_CAT="category"
export const PROD_RAITING="raiting"
export const PROD_IMAGFILE="imageFile"
